import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About | Defiliban',
  description: 'Defiliban is an AI-powered DeFi research platform covering protocols, yield, liquidity, and risk.',
}

const PILLARS = [
  {
    icon: '◈',
    title: 'Data-backed research',
    body: 'Every insight is grounded in onchain data, market metrics, and protocol mechanics — not speculation or hype.',
  },
  {
    icon: '◫',
    title: 'Transparent methodology',
    body: 'All analysis includes sources, confidence scores, and stated assumptions. We show our work.',
  },
  {
    icon: '◉',
    title: 'Editorial independence',
    body: 'Sponsored content is clearly labelled. We do not accept payment for editorial coverage or research conclusions.',
  },
  {
    icon: '◌',
    title: 'Built for professionals',
    body: 'Designed for allocators, researchers, and builders who need actionable intelligence — not a general crypto feed.',
  },
]

const COVERAGE = [
  { label: 'DeFi Protocols', desc: 'DEX mechanics, lending markets, derivatives, stablecoin design, DAO governance' },
  { label: 'Yield Systems', desc: 'Staking mechanics, farming incentives, emission schedules, vault strategies' },
  { label: 'Liquidity Architecture', desc: 'Pool composition, AMM pricing models, cross-protocol capital flows' },
  { label: 'Risk Surfaces', desc: 'Exploit post-mortems, liquidation cascades, smart contract vulnerability analysis' },
  { label: 'Infrastructure', desc: 'Oracle integrity, bridge security, Layer 2 rollup performance' },
]

export default function AboutPage() {
  return (
    <div style={{ background: 'var(--bg-page)', minHeight: '100vh' }}>
      <div style={{ maxWidth: '1280px', margin: '0 auto', padding: 'var(--sp-12) var(--sp-4) var(--sp-16)' }}>

        {/* Hero */}
        <div style={{ maxWidth: '720px', marginBottom: 'var(--sp-16)' }}>
          <p style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '1.5px',
            color: 'var(--text-dim)',
            marginBottom: 'var(--sp-3)',
          }}>
            About Defiliban
          </p>
          <h1 style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '48px',
            fontWeight: 800,
            letterSpacing: '-1px',
            color: 'var(--text-primary)',
            lineHeight: 1.1,
            marginBottom: 'var(--sp-6)',
          }}>
            DeFi research built for those who need to act on it.
          </h1>
          <p style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '18px',
            color: 'var(--text-dim)',
            lineHeight: 1.7,
            marginBottom: 'var(--sp-5)',
          }}>
            Defiliban is an AI-powered research platform that breaks down DeFi protocols, yield systems, liquidity architecture, and risk surfaces — written for professionals, not general audiences.
          </p>
          <p style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '16px',
            color: 'var(--text-dim)',
            lineHeight: 1.65,
          }}>
            Articles are generated by Claude AI from primary sources and reviewed by our editorial team before publishing. Every insight includes a confidence score and source attribution.
          </p>
        </div>

        {/* Pillars */}
        <div style={{ marginBottom: 'var(--sp-16)' }}>
          <p style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '1.5px',
            color: 'var(--text-dim)',
            marginBottom: 'var(--sp-6)',
          }}>
            Our Principles
          </p>
          <div
            className="grid grid-cols-1 sm:grid-cols-2"
            style={{ gap: 'var(--sp-4)' }}
          >
            {PILLARS.map((p) => (
              <div
                key={p.title}
                style={{
                  background: 'var(--bg-surface2)',
                  border: '1px solid var(--border)',
                  borderRadius: '4px',
                  padding: 'var(--sp-6)',
                }}
              >
                <span style={{ fontSize: '20px', color: 'var(--text-dim)', display: 'block', marginBottom: 'var(--sp-3)' }}>
                  {p.icon}
                </span>
                <h3 style={{
                  fontFamily: 'var(--font-sans)',
                  fontSize: '16px',
                  fontWeight: 700,
                  color: 'var(--text-primary)',
                  marginBottom: 'var(--sp-2)',
                }}>
                  {p.title}
                </h3>
                <p style={{
                  fontFamily: 'var(--font-sans)',
                  fontSize: '14px',
                  color: 'var(--text-dim)',
                  lineHeight: 1.6,
                }}>
                  {p.body}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Coverage */}
        <div style={{ marginBottom: 'var(--sp-16)' }}>
          <p style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '1.5px',
            color: 'var(--text-dim)',
            marginBottom: 'var(--sp-2)',
          }}>
            What We Cover
          </p>
          <h2 style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '28px',
            fontWeight: 700,
            letterSpacing: '-0.4px',
            color: 'var(--text-primary)',
            marginBottom: 'var(--sp-8)',
          }}>
            Five verticals. One focus.
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', background: 'var(--border)' }}>
            {COVERAGE.map((c) => (
              <div
                key={c.label}
                style={{
                  background: 'var(--bg-page)',
                  padding: 'var(--sp-5) var(--sp-6)',
                  display: 'flex',
                  alignItems: 'baseline',
                  gap: 'var(--sp-6)',
                  flexWrap: 'wrap',
                }}
              >
                <span style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: '14px',
                  fontWeight: 500,
                  color: 'var(--text-primary)',
                  minWidth: '180px',
                  flexShrink: 0,
                }}>
                  {c.label}
                </span>
                <span style={{
                  fontFamily: 'var(--font-sans)',
                  fontSize: '14px',
                  color: 'var(--text-dim)',
                  lineHeight: 1.5,
                }}>
                  {c.desc}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* AI Pipeline */}
        <div style={{
          background: 'var(--bg-surface2)',
          border: '1px solid var(--border)',
          borderRadius: '4px',
          padding: 'var(--sp-8)',
          marginBottom: 'var(--sp-16)',
        }}>
          <p style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '1.5px',
            color: 'var(--text-dim)',
            marginBottom: 'var(--sp-3)',
          }}>
            How articles are created
          </p>
          <h2 style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '22px',
            fontWeight: 700,
            letterSpacing: '-0.3px',
            color: 'var(--text-primary)',
            marginBottom: 'var(--sp-5)',
          }}>
            AI pipeline + editorial review
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3" style={{ gap: 'var(--sp-4)' }}>
            {[
              { step: '01', label: 'RSS Ingestion', desc: 'Protocol updates, governance posts, and market data from 30+ curated sources.' },
              { step: '02', label: 'Claude Analysis', desc: 'claude-sonnet-4-5 rewrites source material as structured DeFi analysis in our voice.' },
              { step: '03', label: 'Editorial Review', desc: 'Human editors verify accuracy, assign confidence scores, and approve publication.' },
            ].map((s) => (
              <div key={s.step}>
                <span style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: '28px',
                  fontWeight: 500,
                  color: 'var(--text-faint)',
                  display: 'block',
                  marginBottom: 'var(--sp-2)',
                }}>
                  {s.step}
                </span>
                <p style={{
                  fontFamily: 'var(--font-sans)',
                  fontSize: '14px',
                  fontWeight: 600,
                  color: 'var(--text-primary)',
                  marginBottom: 'var(--sp-2)',
                }}>
                  {s.label}
                </p>
                <p style={{
                  fontFamily: 'var(--font-sans)',
                  fontSize: '14px',
                  color: 'var(--text-dim)',
                  lineHeight: 1.55,
                }}>
                  {s.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{ display: 'flex', gap: 'var(--sp-3)', flexWrap: 'wrap' }}>
          <Link
            href="/newsletter"
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '12px',
              textTransform: 'uppercase',
              letterSpacing: '0.8px',
              background: 'var(--text-primary)',
              color: 'var(--bg-void)',
              padding: 'var(--sp-3) var(--sp-6)',
              borderRadius: '20px',
              textDecoration: 'none',
              fontWeight: 500,
            }}
          >
            Get the Newsletter
          </Link>
          <Link
            href="/protocols"
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '12px',
              textTransform: 'uppercase',
              letterSpacing: '0.8px',
              background: 'transparent',
              color: 'var(--text-primary)',
              padding: 'var(--sp-3) var(--sp-6)',
              borderRadius: '20px',
              border: '1px solid var(--border)',
              textDecoration: 'none',
              fontWeight: 500,
            }}
          >
            Browse Research →
          </Link>
        </div>

      </div>
    </div>
  )
}
